[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#1f4e79"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#e8e8e8"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false
